### ISSUE TITLE
Resources to add

### ISSUE THREAD

**Issue by k8hertweck** [fredhutchio/tfcb_2019#1]
- [x] software installation instructions (copied and updated from last year)
- [x] recommended reading list and other resources
- [x] other information required by UW?
- [x] Instructions for non-FH students (for obtaining HutchNetID)

**Comment by k8hertweck** [comment]
currently working on these items in syllabus branch

**Comment by rasi** [comment]
@k8hertweck It will be useful to add install instructions for the tidyverse package (something like [here](https://github.com/rasilab/tfcb_2018/blob/master/lectures/lecture1/how_to_install_r_and_r_studio.org#testing-rstudio)). It is a long install and it will be necessary for running the example Rmarkdown document.

**Comment by k8hertweck** [comment]
Yes, I still need to finish the software install section. Here's the plan:

- R: tidyverse and the following Bioconductor packages: GenomicRanges, VariantAnnotation, GenomeInfoDb, Rsamtools, ggbio, BSgenome.Hsapiens.UCSC.hg38
- Windows Subsystem for Linux, perhaps also Git for Windows as a backup (if anyone is not running Windows 10)
- Python: Biopython (not included in standard Anaconda installation)

**Comment by rasi** [comment]
Bioconductor and Biopython will be definitely useful. Perhaps everyone can chime in regarding the R and Python packages that they intend to use? Then we can make sure that they are installed by the first class.

**Comment by gavinha** [comment]
Hi @k8hertweck 

For my content, we would need to use the following Bioconductor packages:
```
GenomicRanges
VariantAnnotation
GenomeInfoDb
Rsamtools
ggbio
BSgenome.Hsapiens.UCSC.hg38
```

I'll let you know if I can think of more.  

Thanks,
Gavin

**Comment by k8hertweck** [comment]
@rasi @gavinha I'm thinking it might be worth it to include the software install as `install.packages()` in the test script, to make sure folks get everything we need. What do you think of this?

**Comment by rasi** [comment]
> @rasi @gavinha I'm thinking it might be worth it to include the software install as `install.packages()` in the test script, to make sure folks get everything we need. What do you think of this?

Yes, that is a good idea. The Bioconductor packages have a slightly different install command:
https://bioconductor.org/packages/release/bioc/html/GenomicRanges.html

**Comment by k8hertweck** [comment]
Yup, that's why I figured it would be easier to include in a script rather than trying to wrangle the class to get it done!
